basic.forever(function () {
    Tinybit.CarCtrl(Tinybit.CarState.Car_Run)
    basic.pause(1000)
    Tinybit.CarCtrl(Tinybit.CarState.Car_Back)
    basic.pause(1000)
    Tinybit.CarCtrl(Tinybit.CarState.Car_Left)
    basic.pause(1000)
    Tinybit.CarCtrl(Tinybit.CarState.Car_Right)
    basic.pause(1000)
    Tinybit.CarCtrl(Tinybit.CarState.Car_SpinLeft)
    basic.pause(1000)
    Tinybit.CarCtrl(Tinybit.CarState.Car_SpinRight)
    basic.pause(1000)
    Tinybit.CarCtrl(Tinybit.CarState.Car_Stop)
})
